apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: order-service:latest #123456789012.dkr.ecr.us-east-1.amazonaws.com/order-service:latest
        ports:
        - containerPort: 4000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/orderdb"
        - name: USERNAME
          value: "admin"
        - name: PASSWORD
          value: "admin"

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  # type: LoadBalancer